{ pkgs, lib, config, noctalia-shell, ... }:

let
  cfg = config.programs.niri;
  common = import ./common.nix { inherit pkgs; };
  shellConfig = if cfg.shell == "noctalia"
    then import ./shells/noctalia.nix { inherit pkgs noctalia-shell; }
    else import ./shells/inir.nix { inherit pkgs; };
in {
  options.programs.niri = {
    enable = lib.mkEnableOption "niri compositor";
    shell = lib.mkOption {
      type = lib.types.enum [ "noctalia" "inir" ];
      default = "noctalia";
      description = "Which shell to use with niri (noctalia or inir)";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ pkgs.niri ];

    # 選択されたシェルを自動的に有効化
    programs.noctalia-shell.enable = lib.mkDefault (cfg.shell == "noctalia");
    programs.inir.enable = lib.mkDefault (cfg.shell == "inir");

    xdg.configFile."niri/config.kdl".text = ''
// Niri configuration
// Generated by home-manager niri module
// Shell: ${cfg.shell}

// ────────────── Input Configuration ──────────────
${common.input}

// ────────────── Output Configuration ──────────────
${common.output}

// ────────────── Keybindings ──────────────
binds {
${common.commonBinds}

${shellConfig.binds}
}

// ────────────── Startup Applications ──────────────
${common.commonStartup pkgs}
${if cfg.shell == "inir" then shellConfig.startup pkgs else shellConfig.startup}

// ────────────── Misc Settings ──────────────
${common.misc}

// ────────────── Layout Settings ──────────────
${common.layout}

// ────────────── Animation Settings ──────────────
${common.animations}

// ────────────── Window Rules ──────────────
${common.windowRules}

// ────────────── Layer Rules ──────────────
${shellConfig.layerRules}

// ────────────── Environment Variables ──────────────
${common.environment}
    '';
  };
}
