name: Nix Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: statix (lint)
        run: nix run nixpkgs#statix -- check .

      - name: deadnix (dead code)
        run: nix run nixpkgs#deadnix -- --fail .
